### ISSUE TITLE
Ajouter un vêtement dans le panier

### ISSUE THREAD

**Issue by Aigles** [Aigles/Vente-en-ligne#10]
Ajouter un vêtement dans le panier: 
En tant que CLIENT, je veux  AJOUTER OU DES VÊTEMENT(S) dans le panier afin remplir le panier.
Déclencheur :  
L'acheteur choisit un ou plusieurs  vêtement(s) pour ajouter  dans le panier.
Déroulement : 
1.	Le client sélectionner le vêtement désiré  
1.	Le client Cliquez ensuite sur ajouter au panier.
1.	Et enfin il voit un nouvel élément ajouté dans l’icône panier.

**Comment by Velie20** [comment]
Liste des cas de test
1.Le client vérifie si le vêtement choisi est bien celui dans le panier.
2.Le client
