### ISSUE TITLE
Retirer un vêtement dans le panier

### ISSUE THREAD

**Issue by Aigles** [Aigles/Vente-en-ligne#11]

**Comment by JeanDjeda** [comment]
En tant que client , je dois pouvoir clicker sur le boutton "ajouter au panier" pour selectionner un vêtement afin de pouvoir l'acheter

**Comment by Velie20** [comment]
1-un client sélectionne un vêtement qu'il ne souhaitait pas retirer dans le panier. 
1-le client clique pour voir si les vêtements sélectionner sont retirés du panier.
