### ISSUE TITLE
Modifier un utilisateur

### ISSUE THREAD

**Issue by Josiase** [Aigles/Vente-en-ligne#24]

**Comment by nerlan** [comment]
Modifier un utilisateur
En tant que ADMINISTRATEUR, je veux modifier un utilisateur afin de metrre a jours la liste des utilisateurs.
Pré-Condition : L’ADMINISTRATEUR doit s’authentifier
Déclencheur : LADMINISTRATEUR entre dans le système
Déroulement :
VEL affiche tous les utilisateurs.
1. LADMINISTRATEUR recherche l’utilisateur qu’il souhaite modifier.
2. L’ADMINISTRATEUR clique sur l’utilisateur qu’il veut modifier.
3. L’ADMINISTRATEUR clique sur l’onglet « MODIFIER UN UTILISATEUR ».
4. VEL affiche tous les champs.
5. LADMINISTRATEUR clique sur le champ qu’il souhaite modifier.

**Comment by nerlan** [comment]
Liste de cas de test
1-LADMINISTRATEUR remplit tous les champs.
1.1	LADMINISTRATEUR clique sur l’utilisateur qu’il ne souhaite pas modifier.
1.2	LADMINISTRATEUR entre un utilisateur qui n’existe pas.
