### ISSUE TITLE
Lister client

### ISSUE THREAD

**Issue by Josiase** [Aigles/Vente-en-ligne#25]

**Comment by Velie20** [comment]
En tant qu'administrateur je veux lister tous les clients 
pre-condition: l'administrateur s'authentifie
declencheur:l'administrateur cherche une information sur un client
scenario:
1-L'administrateur clique sur client.
2-VEL deroule un menu
3-L'administrateur clique sur lister client.
4-VEL affiche la liste des clients avec leurs informations personnelles.


LIste des cas de test
1-L'administrateur clique sur lister client.
