### ISSUE TITLE
Tableau de bord

### ISSUE THREAD

**Issue by Josiase** [Aigles/Vente-en-ligne#26]

**Comment by Velie20** [comment]
En tant qu'administrateur je veux faire une statistique sur comment marche l'application
pre-condition: L'administrateur s'authentifie
declencheur: L'administrateur veut avoir un compte rendu
scenario: 
1- L'administrateur clique sur tableau de bord
2-VEL affiche une fenetre qui donne une statistique sur les personnels, les produits, les commandes et les clients.

Liste des cas de test
1- L'administrateur clique sur tableau de bord.
2- L'administrateur verifie si les nombre de personnels, de produits, de commandes et de clients sont adequats aux vraies valeurs.
3- L'administrateur verifie si les nouveaux personnels, les nouveaux produits, les nouvelles commandes et les nouveaux clients sont notees dans une" tooltip".
4- L'administrateur verifie si sur chaque nouvelle commande  la graphe pie est modifiee.
5- L'administrateur verifie que chaque nouvelle livraison est notee sur le calendrier.
