### ISSUE TITLE
Vider le panier

### ISSUE THREAD

**Issue by Josiase** [Aigles/Vente-en-ligne#27]

**Comment by Velie20** [comment]
En tant que client je veux VIDER MON PANIER apres avoir commande 
pré-condition: le client s'authentifie
Déclencheur:le client va dans son panier
Déroulement: 
1-le client clique sur le panier.
2-VEL affiche la liste des produits du panier.
3-le client clique sur vider le panier. 
4-VEL supprime tous les produits du panier.


Liste des cas de test:
1-le client clique sur vider le panier --> VEL a vidé le panier et aucun produit ne s'y trouve.
