### ISSUE TITLE
Rechercher un vêtement

### ISSUE THREAD

**Issue by Aigles** [Aigles/Vente-en-ligne#3]
En tant que client je veux RECHERCHER UN VETEMENT afin de faire un achat
Déclencheur : Le client est entré dans VEL et il sélectionne le champ « Rechercher ». 
Déroulement:
Client 	
1.	Le client  entre dans le système pour rechercher un vêtement.
1.	Le client clique sur le champ « Rechercher » pour saisir le nom d’un vêtement.
1.	Le client clique sur le bouton Rechercher pour valider.
1.	VEL affiche le vêtement et sa description selon le nom qui a été saisi.

**Comment by Fendoue** [comment]
Liste des cas de Test :
1. Le client saisit un nom de vêtement qui n'existe pas  dans VEL.
1. Le client saisit un nom de vêtement qui existe dans VEL
