### ISSUE TITLE
Authentifier Administrateur

### ISSUE THREAD

**Issue by Aigles** [Aigles/Vente-en-ligne#6]
Authentifier un Administrateur
En tant que Administrateur, je veux m’AUTHENTIFIER afin  de mettre à jour le système 
Déclencheur : Le client entre sur le site et clique sur l’onglet Authentifier.

1. VEL affiche les différents champs.
1. L’Administrateur  entre son adresse mail et son mot de passe.
1. L’Administrateur peut cliquer sur l’onglet connecté.
En cas où l’Administrateur a oublié son mot de passe
1. L’Administrateur doit cliquer sur l’onglet  « Mot de passe oublié ».
1. VEL affiche les champs.
1. L’Administrateur entre son adresse  mail
1. L’Administrateur peut cliquer sur l’onglet « réinitialiser le mot de passe » « ou reset password»

**Comment by Velie20** [comment]
Liste des cas de test
1.L'administrateur doit saisir tous les champs qui sont adéquats.
2.L'administrateur doit saisir tous les champs où certains champs obligatoires n'ont pas été complétés  (ex:password).
3.L'administrateur doit saisir tous les champs où au moins un des champs est inapproprié.
