### ISSUE TITLE
Authentifier Client

### ISSUE THREAD

**Issue by Aigles** [Aigles/Vente-en-ligne#7]
Authentifier un Client
En tant que CLIENT, je veux m’AUTHENTIFIER afin d’ACHETER  UN VȆTEMENT.
Déclencheur : Le client entre sur le site et clique sur l’onglet Authentifier.

1. VEL affiche les différents champs.
1. Le client entre son adresse mail et son mot de passe.
1. Le client peut cliquer sur l’onglet connecté.
En cas où le client a oublié son mot de passe
1. Le client doit cliquer sur l’onglet  « Mot de passe oublié ».
1. VEL affiche les champs.
1. Le client entre son adresse  mail
1. Le client peut cliquer sur l’onglet « réinitialiser le mot de passe » « ou reset password»

**Comment by Velie20** [comment]
Liste des cas de test
1.Le client doit saisir tous les champs qui sont adéquats .
2.Le client doit saisir tous les champs où certains champs obligatoires n'ont pas été complétés (ex:e-mail,password)
3.Le client doit saisir des champs où au moins un des champs est inapproprié
